config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
 
  root 'splash#index'
  resources :users
  resources :groups, only: [:index, :show, :new, :create]
  resources :expenses, only: [:index, :show, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses
  has_many :groups, through: :group_expenses
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy, foreign_key: 'group_id'
  has_one_attached :icon

  validates :name, presence: true, length: { maximum: 50 }
  validate :icon_format
  validate :icon_presence

  private

  def icon_format
    return unless icon.attached? && !icon.content_type.in?(%w[image/jpeg image/png])

    errors.add(:icon, 'needs to be a jpeg or png!')
  end

  def icon_presence
    return if icon.attached?

    errors.add(:icon, 'must be attached')
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, foreign_key: 'author_id'
  has_many :groups, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, unless: :public_page?
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_out_path_for(_resource)
    root_path # splash path
  end

  def after_sign_in_path_for(_resource)
    groups_path # groups path
  end

  def public_page?
    controller_name == 'splash' && action_name == 'index'
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:group_id].present?
      @group = Group.find(params[:group_id])
      @group_expenses = GroupExpense
        .includes(:expense)
        .where(group_id: params[:group_id])
        .order(created_at: :desc)

      @total_amount = @group_expenses.sum { |trans| trans.expense.amount }

      render 'index', group: @group, total_amount: @total_amount
    else
      @expenses = Expense.where(author_id: current_user.id)
      render 'index', expenses: @expenses
    end
  end

  def new
    @groups = Group.where(author_id: current_user.id)
    @groups = @groups.map do |group|
      [group.name, group.id]
    end
    render 'new'
  end

  def create
    name = params[:expense][:name]
    amount = params[:expense][:amount]
    group_id = params[:expense][:group]
    expense = Expense.create(name:, amount:, author_id: current_user.id)
    group_expense = GroupExpense.create(group_id:, expense_id: expense.id)
    if expense.save && group_expense.save
      flash[:success] = 'Group saved successfully'
      redirect_to groups_path
    else
      @groups = Group.where(author_id: current_user.id)
      @groups = @groups.map do |group|
        [group.name, group.id]
      end
      flash[:error] = 'Group couldn`t be saved'
      render 'new'
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = current_user.groups
    @user = current_user
  end

  def new
    @group = current_user.groups.build
    @user = current_user
  end

  def create
    @group = Group.new(group_params)
    @group = current_user.groups.build(group_params)

    if @group.valid? && @group.save
      redirect_to groups_path(current_user), notice: 'Category added successfully'
    else
      flash.now[:error] = 'Failed to add category'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :created_at)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expense_helper.rb
module ExpenseHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/expenses/index.html.erb
<h1 class="uppercase text-center text-2xl mb-5 md:text-3xl">Transactions</h1>
<% if @group.present? %>
<div class="flex items-center justify-between mb-4 mx-4 md:mx-20">
<%= link_to "&larr;".html_safe, groups_path, class: "text-4xl mb-3 text-black font-bold" %>
<h2 class=" text-center uppercase text-green-custom text-2xl font-bold mb-4 md:text-2xl"><%= @group.name %></h1>
</div>
<p class="bg-white shadow-md rounded-lg mb-4 p-4 mx-10 flex justify-between items-center w-64 mx-auto md:w-2/4"><span>Total Spent</span><%= number_to_currency(@total_amount) %> </p>
<% end %>

<% if @group_expenses %>
  <% @group_expenses.each do |expense| %>
    <div class="bg-white shadow-md rounded-lg mb-4 p-4 flex flex-col gap-6 w-64 mx-auto md:w-2/4">
    <div class="flex justify-between">
      <p><%= expense.expense.name.capitalize %></p>
      <p>Amount: <%= number_to_currency(expense.expense.amount) %></p>
      </div>
      <p><%= expense.created_at.to_date %></p>
    </div>
  <% end %>
<% else %>
  <p>No expenses found for this group.</p>
<% end %>
<div class="text-center mt-8">
<%= link_to "Add a new transaction", new_expense_path, class: " p-2 inline-flex justify-center items-center border border-green-custom" %>
</div>

app/views/expenses/new.html.erb
<h1 class="uppercase text-center text-3xl">Add Transaction</h1>
<%= form_with model: @expense, html: { class: "flex flex-col gap-4 m-8 items-center" }, url: expenses_path, scope: :expense do |f|%>

<div>
    <%= f.label :name, hidden: true %><br>
    <%= f.text_field :name, placeholder: 'Transaction Name' %>
  </div>

  <div>
    <%= f.label :amount, hidden: true %><br>
    <%= f.number_field :amount, placeholder: 'Amount' %>
  </div>

  <div>
    <%= f.label :group, hidden: true %><br>
    <%= f.select :group, @groups, selected: @groups[0][1] %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: " p-1 inline-flex justify-center items-center border border-green-custom w-32 cursor-pointer text-teal-900" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<h1 class="uppercase text-center text-green-custom text-3xl font-bold">Categories</h1>

<ul class=" p-8">
  <% @groups.each do |group| %>
  <%= link_to expenses_path(group_id: group.id) do %>
    <li class="flex justify-center gap-6 items-center bg-white shadow-md rounded-lg mb-4 p-2 mx-auto md:w-2/4">
    <%= image_tag rails_blob_path(group.icon), class: "w-16 h-16" if group.icon.attached? %>
      <p class="whitespace-nowrap text-gray-600"><%= group.name %></p>
      <p class="whitespace-nowrap">Total spent: $<%= number_with_precision(group.expenses.sum(:amount), precision: 2) %></p>
    </li>
  <% end %>
   <% end %>

</ul>
<div class="text-center mt-8">
<%= link_to "Add a new category", new_group_path, class: " p-2 inline-flex justify-center items-center border border-green-custom mb-8" %>
</div>

app/views/groups/new.html.erb
<div class="flex items-center justify-between mx-4 md:mx-20"><%= link_to "&larr;".html_safe, groups_path, class: "text-5xl mb-3 text-black font-bold" %>
<h1 class="uppercase text-center text-green-custom text-2xl">
Create New Category</h1>
</div>
<%= form_for @group, html: { class: "flex flex-col gap-4 m-8 items-center" }  do |f| %>
  <div class="flex flex-col gap-2">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :icon %>
    <%= f.file_field :icon %>
  </div>

  <%= f.submit "Save", class: " p-1 inline-flex justify-center items-center border border-green-custom w-32 cursor-pointer text-teal-900" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 h-screen">
    <main class="bg-white bg-opacity-20 backdrop-blur-xl rounded h-screen">
  <% if user_signed_in? %>
  <header class="mb-8 py-4 shadow-md rounded-lg bg-blue-two-custom">
    <nav class="flex justify-center items-center gap-1 md:gap-4 text-white">    
      Welcome <strong><%= current_user.name %></strong> | 
      <%= link_to "Categories", groups_path, class: "navbar-link" %> |
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |   
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-link" %>
    </nav>
  </header>
<% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/splash/index.html.erb
<div class=" flex flex-col justify-center items-center gap-8 px-4 pt-32">
  <h1 class="font-bold text-3xl text-green-custom text-center">Welcome to Expense App!</h1>
  <p class="text-center text-base">Get started by signing up or logging in.</p>
  <div class="flex gap-8">
  <div class='btn btn-primary'>
  <%= link_to 'Sign up', new_user_registration_path%>
  </div>
  <div class='btn btn-secondary'>
  <%= link_to 'Log in', new_user_session_path%>
  </div>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <h1 class="font-bold text-4xl">User#index</h1>
  <p>Find me in app/views/user/index.html.erb</p>
</div>

app/views/users/show.html.erb
<div>
  <h1 class="font-bold text-4xl">User#show</h1>
  <p>Find me in app/views/user/show.html.erb</p>
</div>